version: '3.3'
services:
  server:
    image: quizapi
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/quiz?useSSL=false
    networks:
      - spring-mysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - spring-mysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=coderslab
      - MYSQL_DATABASE=quiz
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=coderslab
    ports:
      - "3307:3307"
    expose:
      - "3307"

networks:
  spring-mysql-net: